/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.order.system.kafka.order.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum StockOrderStatus implements org.apache.avro.generic.GenericEnumSymbol<StockOrderStatus> {
  PAID  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"StockOrderStatus\",\"namespace\":\"com.order.system.kafka.order.avro.model\",\"symbols\":[\"PAID\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
